### ISSUE TITLE
Problemă estetică legată de descrierea cluburilor.

### ISSUE THREAD

**Issue by PinzariuAlbert** [RobertPietraru/laurian#24]
Să spunem că trebuie să adaug o descriere foarte lungă pentru că am multe informații de pus. Pe pagina "Cluburi" stă urât tot textul afișat acolo. Plus, dacă toată descrierea este afișată în "Cluburi" care este rostul butonului "află mai multe" dacă nu mai ai ce afla.

Cred că dacă descrierea afișată pe pagina "Cluburi" s-ar opri la... 50 de caractere să spunem, pagina o să arate mult mai organizat.

**Comment by RobertPietraru** [comment]
Duplicate of #8

**Comment by RobertPietraru** [comment]
Chiar daca am inchis issue-ul, e bine facut, doar ca avem deja unul pentru problema asta.

Deci nu te descuraja!
